config/routes.rb
Rails.application.routes.draw do
  post "payment/create", to: "payment#create", as: "payment_create"
  get "payment/success", to: "payment#success", as: "payment_success"
  get "payment/cancel", to: "payment#cancel", as: "payment_cancel"
  post "order/destroy/:id", to: "orders#destroy", as: "order_delete"
  resources :orders, only: %i[show new create]
  # get "checkout", to: "checkout#index", as: "checkout"

  post "cart/:id", to: "cart#create", as: "cart_create"
  post "cart/delete/:id", to: "cart#destroy", as: "cart_delete"
  post "cart/update/:id", to: "cart#update", as: "cart_update"

  resources :catagories, only: [:show]
  resources :addresses, only: %i[new create]

  resources :sessions, only: %i[new create destroy]
  get "logout", to: "sessions#destroy", as: "logout"

  resources :users, only: %i[show new create]

  resources :products, only: %i[index show]
  resources :checkout, only: [:index]

  root to: "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
    @items = []
    cart["items"].each do |item|
      product = Product.find(item["id"])
      @items.push({
                    item:    item,
                    product: product
                  })
    end
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/checkout/index.html.erb
<section class="hero is-info mb-5">
  <div class="hero-body">
    <div class=container>
      <h1 class="title is-3">Checkout</h1>
      <h1 class="subtitle"><%=pluralize cart["amount"], "Game"%></h1>
    </div>
  </div>
</section>

<div class="container">

  <%@items.each do |item|%>
      <div class="columns pb-5 mt-5 mb-5 border-bottom">
        <div class=column>
          <p class=""><%= item[:product].name %> x
            <%=item[:item]["amount"]%>
            | <%= number_to_currency item[:product].price * item[:item]["amount"]%> total.</p>
        </div>
        <div class="column is-1" style="direction:rtl">
          <div class="columns">
            <div class="column">
                <%=form_with url: cart_delete_path(item[:product].id) do%>
                  <%= hidden_field_tag :id, item[:product].id %>
                  <%= button_tag 'x', class: "button is-danger mr-5" %>
                <%end%>
            </div>

            <div class="column">
              <%=form_with url: cart_update_path(item[:product].id) do%>
                <%= hidden_field_tag :id, item[:product].id %>
                <%= hidden_field_tag :add, true %>
                <%= button_tag '▲', class: "button is-warning mr-5" %>
              <%end%>
            </div>

            <div class=column>
              <%=form_with url: cart_update_path(item[:product].id) do%>
                <%= hidden_field_tag :id, item[:product].id %>
                <%= hidden_field_tag :add, false %>
                <%= button_tag '▼', class: "button is-warning mr-5" %>
              <%end%>
            </div>
          </div>



        </div>
      </div>


  <%end%>
  <div class="columns  mb-5">
    <div class="column">
      <h1 class="subtitle"> SubTotal: <%= number_to_currency cart_subtotal%></h1>
    </div>
    <div>
      <a href="<%= new_order_path %>" class="button is-success"> Place Order</a>
    </div>
  </div>

</div>