config/routes.rb
Rails.application.routes.draw do
  post "payment/create", to: "payment#create", as: "payment_create"
  get "payment/success", to: "payment#success", as: "payment_success"
  get "payment/cancel", to: "payment#cancel", as: "payment_cancel"
  post "order/destroy/:id", to: "orders#destroy", as: "order_delete"
  resources :orders, only: %i[show new create]
  # get "checkout", to: "checkout#index", as: "checkout"

  post "cart/:id", to: "cart#create", as: "cart_create"
  post "cart/delete/:id", to: "cart#destroy", as: "cart_delete"
  post "cart/update/:id", to: "cart#update", as: "cart_update"

  resources :catagories, only: [:show]
  resources :addresses, only: %i[new create]

  resources :sessions, only: %i[new create destroy]
  get "logout", to: "sessions#destroy", as: "logout"

  resources :users, only: %i[show new create]

  resources :products, only: %i[index show]
  resources :checkout, only: [:index]

  root to: "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
require "net/http"
require "json"

#======================
# Order
#
# Represents Order table in database.
#
# Feilds
# --------------------------
# Total Price | Decimal | Required, Numeric
# State       | String  | Requried
#
# Assocations
# --------------------
# Belongs to a User
# Has One Address
# Has Many OrderedItems
# Has Many Products via OrderedItems
#
#======================

class Order < ApplicationRecord
  NEW = "new".freeze
  PROCESSING = "processing".freeze
  SHIPPED = "shipped".freeze
  DELIVERED = "delivered".freeze
  CANCELLED = "cancelled".freeze

  def item_string
    "#{products.first.name}, and more..."
  end

  def tax_resource
    tax_url = "https://api.salestaxapi.ca/v2/province/#{address.state}"
    tax_uri = URI(tax_url)
    JSON.parse(Net::HTTP.get(tax_uri))
  end

  def gst
    tax_res = tax_resource

    total_price * tax_res["gst"]
  end

  def pst
    tax_res = tax_resource
    total_price * tax_res["pst"]
  end

  def total_taxed_price
    tax_res = tax_resource
    gst = total_price * tax_res["gst"]
    pst = total_price * tax_res["pst"]
    total_price + gst + pst
  end

  validates :total_price, :state, presence: true
  validates :total_price, numericality: true
  validates :state, inclusion: { in: [NEW, SHIPPED, PROCESSING, DELIVERED, CANCELLED] }

  belongs_to :user, optional: true
  belongs_to :address
  has_many :ordered_items
  has_many :products, through: :ordered_items
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  SAVED_ADDRESS_TYPE = "saved_address".freeze
  NEW_ADDRESS_TYPE = "new_address".freeze

  def new
    @order = Order.new
  end

  def create
    type_of_address = params[:type]

    if type_of_address == SAVED_ADDRESS_TYPE
      address = Address.find(params[:address_id])
    elsif type_of_address == NEW_ADDRESS_TYPE
      address = Address.create(line1:      params[:line1],
                               line2:      params[:line2],
                               city:       params[:city],
                               state:      params[:state],
                               country:    params[:country],
                               phone:      params[:phone],
                               postalCode: params[:postalCode])

      current_user.address = address if params[:save]
    end

    new_order = Order.create(total_price: 0,
                             state:       Order::NEW,
                             address:     address,
                             user:        logged_in? ? current_user : User.find_by(name: "guest"))

    logger.debug(new_order.errors.messages) unless new_order.valid?

    total = 0

    cart["items"].each do |item|
      product = Product.find(item["id"])
      logger.debug(product.name)
      item = new_order.ordered_items.create(amount:  item["amount"],
                                            price:   product.price,
                                            product: product)
      total += item["amount"] * product.price
      logger.debug(item.errors.messages) unless item.valid?
    end
    new_order.total_price = total
    new_order.save

    session["cart"]["items"] = []
    session["cart"]["amount"] = 0

    redirect_to order_path(new_order.id)
  end

  def show
    @order = Order.find(params[:id])

    if current_user.nil? && @order.user.id != 5
      redirect_to root_path
      return
    end

    redirect_to root_path if @order.user.id != current_user.id
  end

  def destroy
    order = Order.find(params[:id])
    order.state = Order::CANCELLED
    order.save
    redirect_to user_path(current_user.id)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/new.html.erb
<section class="hero is-info mb-5">
  <div class="hero-body">
    <div class=container>
      <h1 class="title is-3">Address for Delivery</h1>
    </div>
  </div>
</section>


<%if logged_in? %>
  <h1 class="title is-4">Choose one of your addresses</h1>
  <div class="mb-5">
    <%= form_with url: orders_path(1) do%>
      <%=label :address_id, "Address"%>
      <%=select_tag :address_id, options_from_collection_for_select(current_user.addresses, :id, :line1) %>
      <%=submit_tag "Use this Address", class: "button is-primary"%>
      <%=hidden_field_tag :type, "saved_address"%>
    <%end%>
  </div>
  <h1 class="title is-4">Or</h1>
<%end%>

  <div>
    <h1>Create new Address </h1>
    <%= form_with url: orders_path(1) do%>
    <p>
      <%= label :line1, "Line 1:"%>
      <%= text_field_tag :line1%>
    </p>
    <p>
      <%= label :line2, "Line 2:"%>
      <%= text_field_tag :line2%>
    </p>
    <p>
      <%= label :city, "City:"%>
      <%= text_field_tag :city%>
    </p>
    <p>
      <%= label :state, "State:"%>
      <%= text_field_tag :state%>
    </p>
    <p>
      <%= label :country, "Country:"%>
      <%= text_field_tag :country%>
    </p>
    <p>
      <%= label :phone, "Phone:"%>
      <%= text_field_tag :phone%>
    </p>
    <p>
      <%= label :postalCode, "Postal Code:"%>
      <%= text_field_tag :postalCode%>
    </p>
    <% if logged_in? %>
      <p>
        <%= label :save, "Save Address:"%>
        <%= check_box_tag :save%>
      </p>
    <%end%>
    <p>
      <%= submit_tag "Use this address", class: "button is-primary" %>
    </p>
    <%= hidden_field_tag :type, "new_address"%>
    <%end%>
  </div>

app/views/orders/show.html.erb
<section class="hero is-info mb-5">
  <div class="hero-body">
    <div class=container>
      <h1 class="title is-3">My Order</h1>
      <h1 class=subtitle>Order Status: <%=@order.state%></h1>
    </div>
  </div>
</section>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Amount</th>
      <th>Price</th>
      <th>Total Price</th>
    </tr>
  </thead>
  <tbody>
    <%@order.ordered_items.each do |item|%>
      <tr>
        <td><%= image_tag item.product.image.variant(resize: "100x150!").processed, alt: item.product.name %></td>
        <td><%= item.product.name%></td>
        <td><%= item.amount%></td>
        <td><%= number_to_currency item.price%></td>
        <td><%= number_to_currency item.price * item.amount%></td>
      </tr>
    <%end%>
  </tbody>
</table>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>Sub-Total</th>
      <th>GST</th>
      <th>PST</th>
      <th>Grand Total</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= number_to_currency @order.total_price %></td>
      <td><%= number_to_currency @order.pst %></td>
      <td><%= number_to_currency @order.gst %></td>
      <td><%= number_to_currency @order.total_taxed_price %></td>
    </tr>
  </tbody>
</table>

<%if @order.state == Order::NEW%>

  <section class="hero is-info mb-5">
    <div class="hero-body">
      <div class=container>
        <div class="is-flex" style="justify-content: space-between">
          <h1 class="title is-3">Pay for Order</h1>
          <%=form_with url: order_delete_path(@order.id) do%>
            <%= hidden_field_tag :id, @order.id %>
            <%= button_tag 'Cancel Order', class: "button is-danger mr-5" %>
          <%end%>
        </div>
      </div>
    </div>
  </section>

  <%=form_with url: payment_create_path do%>
    <%= hidden_field_tag :id, @order.id %>
    <%= button_tag 'Pay With Stripe 💳', class: "button is-info mr-5" %>
  <%end%>

<%elsif @order.state == Order::PROCESSING%>

  <section class="hero is-primary mb-5">
    <div class="hero-body">
      <div class=container>
        <div class="is-flex" style="justify-content: space-between">
          <h1 class="title is-3">Your Order is Being Processed...</h1>
        </div>
      </div>
    </div>
  </section>

<%elsif @order.state == Order::SHIPPED%>

  <section class="hero is-primary mb-5">
    <div class="hero-body">
      <div class=container>
        <div class="is-flex" style="justify-content: space-between">
          <h1 class="title is-3">Your Order is On Its Way!</h1>
        </div>
      </div>
    </div>
  </section>

<%elsif @order.state == Order::DELIVERED%>

  <section class="hero is-success mb-5">
    <div class="hero-body">
      <div class=container>
        <div class="is-flex" style="justify-content: space-between">
          <h1 class="title is-3">Your Order has Arrived!</h1>
        </div>
      </div>
    </div>
  </section>

<%elsif @order.state == Order::CANCELLED%>

  <section class="hero is-danger mb-5">
    <div class="hero-body">
      <div class=container>
        <div class="is-flex" style="justify-content: space-between">
          <h1 class="title is-3">This Order was Cancelled.</h1>
        </div>
      </div>
    </div>
  </section>

<%end%>