config/routes.rb
Rails.application.routes.draw do
  post "payment/create", to: "payment#create", as: "payment_create"
  get "payment/success", to: "payment#success", as: "payment_success"
  get "payment/cancel", to: "payment#cancel", as: "payment_cancel"
  post "order/destroy/:id", to: "orders#destroy", as: "order_delete"
  resources :orders, only: %i[show new create]
  # get "checkout", to: "checkout#index", as: "checkout"

  post "cart/:id", to: "cart#create", as: "cart_create"
  post "cart/delete/:id", to: "cart#destroy", as: "cart_delete"
  post "cart/update/:id", to: "cart#update", as: "cart_update"

  resources :catagories, only: [:show]
  resources :addresses, only: %i[new create]

  resources :sessions, only: %i[new create destroy]
  get "logout", to: "sessions#destroy", as: "logout"

  resources :users, only: %i[show new create]

  resources :products, only: %i[index show]
  resources :checkout, only: [:index]

  root to: "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
#======================
# Product
#
# Represents User table in database.
#
# Feilds
# --------------------------
# Name        | String      | Required
# Price       | Decimal     | Requried, Numeric
# Stock       | Integer     | Requried, Numeric, Integer
# Image       | Attachment  | Optional
# Description | Text        | Optional
#
# Assocations
# --------------------
# Belongs to a Catagory
# Has Many OrderedItems
# Has Many Orders via OrderedItems
#
#======================

class Product < ApplicationRecord
  NEW_PRODUCT_THRESHOLD = 3
  RECENT_UPDATE_THRESHOLD = 3

  NEW_ID = "1".freeze
  RECENTLY_UPDATED_ID = "2".freeze

  PRICE_ID = "1".freeze
  STOCK_ID = "2".freeze
  NAME_ID =  "3".freeze

  def self.new_products
    Product.where(new_products_query)
  end

  def self.new_products_query
    if Rails.env.development?
      "julianday('now') - julianday(created_at) <= #{NEW_PRODUCT_THRESHOLD}"
    else
      "DATE_PART('day', current_timestamp-created_at) <= #{NEW_PRODUCT_THRESHOLD}"
    end
  end

  def self.recently_updated_products
    Product.where
  end

  def self.recently_updated_products_query
    if Rails.env.development?
      "julianday('now') - julianday(created_at) <= #{RECENT_UPDATE_THRESHOLD} AND NOT (#{new_products_query})"
    else
      "DATE_PART('day', current_timestamp-updated_at) <= #{RECENT_UPDATE_THRESHOLD} AND NOT (#{new_products_query})"
    end
  end

  def self.generate_filter_url(params)
    "/products?query=#{params[:query] || ''}&console_id=#{params[:console_id] || ''}&filter_id=#{params[:filter_id] || ''}&page=#{params[:page] || ''}"
  end

  def self.generate_paged_filter_url(params, page)
    "/products?query=#{params[:query] || ''}&console_id=#{params[:console_id] || ''}&filter_id=#{params[:filter_id] || ''}&page=#{page}"
  end

  def self.sort_by(products, sort_id, dir)
    if sort_id.present?
      sort_dir = dir == "0" ? "DESC" : "ASC"
      products = products.order("price #{sort_dir}") if sort_id == PRICE_ID # Sort by Price
      products = products.order("stock #{sort_dir}") if sort_id == STOCK_ID # Sort by Stock
      products = products.order("name #{sort_dir}") if sort_id == NAME_ID   # Sort by Name
    end

    products
  end

  def self.get_filtered_products(params)
    products = Product.all

    products = filter_all_products_by_catagory(products, params[:console_id])

    page = 1
    page = params[:page].to_i if params[:page].present?
    products = get_product_page(products, page)

    products = filter_products(products, params[:filter_id])

    if params[:query].present?
      products = products.where("name LIKE :query", query: "%#{params[:query]}%")
    end

    products = sort_by(products, params[:sort_id], params[:sort_dir])

    products
  end

  def self.filter_products(products, filter_id)
    if filter_id.present?
      if filter_id == NEW_ID # Filter by new Products.
        products = products.where(Product.new_products_query)
      elsif filter_id == RECENTLY_UPDATED_ID # Filter by Recently updated products.
        products = products.where(Product.recently_updated_products_query)
      end
    end

    products
  end

  def self.filter_all_products_by_catagory(products, catagory_id)
    if catagory_id.present?
      catagory = Catagory.find(catagory_id)
      products = catagory.products
    end
    products
  end

  def self.get_product_page(products, page)
    products = products.page(page)
    products
  end

  validates :name, :price, :stock, presence: true
  validates :price, numericality: true
  validates :stock, numericality: [only_integer: true]

  belongs_to :catagory
  has_many :ordered_items
  has_many :orders, through: :ordered_items

  has_one_attached :image

  max_paginates_per 8
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @catagories = Catagory.all
    @products = Product.get_filtered_products(params)
    @page = params[:page].present? ? params[:page].to_i : 1
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<section class="hero is-info mb-5">
  <div class="hero-body">
    <div class=container>
      <h1 class="title is-3">All Products</h1>
    </div>
  </div>
</section>

<div class="columns">
  <div class="column is-one-fifth mr-5" style="border-right: 1px gray dashed">

    <form action="<%= products_path %>" method="get">
      <p>
        <label for="searcg">Search: </label>
        <input type="text" name="query" id="query">
      </p>
      <p>
        <label for="console">Console: </label>
        <%= select_tag :console_id, options_from_collection_for_select(@catagories, :id, :name), include_blank: true %>
      </p>
      <p>
        <label for="filter">Filter By: </label>
        <%= select_tag :filter_id, options_for_select([
          ["New", Product::NEW_ID],
          ["Recently Updated", Product::RECENTLY_UPDATED_ID]
        ]), include_blank: true%>
      </p>
      <p>
        <label for="sort_by">Sort By: </label>
        <%= select_tag :sort_id, options_for_select([
          ["Price", 1],
          ["Stock", 2],
          ["Name",  3]
        ]), include_blank: true%>
        <%= select_tag :sort_dir, options_for_select([
          ["▼", 0],
          ["▲", 1]
        ])%>
      </p>
      <p>
        <input type="submit" value="Filter">
      </p>
    </form>
  </div>

  <div class="column">
    <div class="columns is-multiline">
      <%= render partial: "common/product_card",
              collection: @products,
              as: :product,
              locals: {size: "is-one-quarter"}%>
    </div>

    <nav class="pagination is-centered" role="navigation" aria-label="pagination">
      <%if @page != 1 %>
        <a class="pagination-previous" href="<%= Product.generate_paged_filter_url(params, @page-1)%>">Previous</a>
      <%end%>

      <%if @page != @products.total_pages %>
        <a class="pagination-next" href="<%= Product.generate_paged_filter_url(params, @page+1)%>">Next page</a>
      <%end%>

      <ul class="pagination-list">
        <%if @page != 1 %>
          <li><a class="pagination-link" aria-label="Goto page 1" href="<%= Product.generate_paged_filter_url(params, 1)%>">1</a></li>
          <li><span class="pagination-ellipsis">&hellip;</span></li>
          <li><a class="pagination-link" aria-label="Goto page <%= @page-1 %>"  href="<%= Product.generate_paged_filter_url(params, @page-1)%>"><%= @page-1 %></a></li>
        <%end%>

        <li><a class="pagination-link is-current" aria-label="Page <%= @page %>"  aria-current="page"><%= @page %></a></li>

        <%if @page != @products.total_pages %>
          <li><a class="pagination-link" aria-label="Goto page <%= @page+1 %>" href="<%= Product.generate_paged_filter_url(params, @page+1)%>"><%= @page+1 %></a></li>
          <li><span class="pagination-ellipsis">&hellip;</span></li>
          <li><a class="pagination-link" aria-label="Goto page <%= @products.total_pages %>" href="<%= Product.generate_paged_filter_url(params, @products.total_pages)%>"><%= @products.total_pages %></a></li>
        <%end%>
      </ul>
    </nav>
  </div>
</div>

app/views/products/show.html.erb
<section class="hero is-info mb-5">
  <div class="hero-body">
    <div class=container>
      <h1 class="title is-3"><%= @product.name %></h1>
      <h1 class="subtitle is-italic"><%= @product.catagory.name %> | $<%= @product.price %> CAD</h1>
    </div>
  </div>
</section>

<div class="columns">
  <div class="column is-one-third mr-5" style="border-right: 1px dashed grey">

    <div class="container is-flex mb-5" style="justify-content:center">
      <%= image_tag @product.image.variant(resize: "1024x800!").processed, alt: @product.name%>
    </div>

    <div class="container is-flex" style="justify-content:center">
      <div class=is-flex style="justify-content:center; align-items:center">

        <%=form_with url: cart_create_path do%>
          <%= hidden_field_tag :id, @product.id %>
          <%= button_tag 'Add to Cart', class: "button is-success mr-5" %>
        <%end%>

        <p class=is-italic>$<%= @product.price %> CAD | <%= @product.stock%> left.</p>
      </div>
    </div>

  </div>

  <div class="column">
    <p><%= @product.description %></p>
  </div>

</div>