config/routes.rb
Rails.application.routes.draw do
  post "payment/create", to: "payment#create", as: "payment_create"
  get "payment/success", to: "payment#success", as: "payment_success"
  get "payment/cancel", to: "payment#cancel", as: "payment_cancel"
  post "order/destroy/:id", to: "orders#destroy", as: "order_delete"
  resources :orders, only: %i[show new create]
  # get "checkout", to: "checkout#index", as: "checkout"

  post "cart/:id", to: "cart#create", as: "cart_create"
  post "cart/delete/:id", to: "cart#destroy", as: "cart_delete"
  post "cart/update/:id", to: "cart#update", as: "cart_update"

  resources :catagories, only: [:show]
  resources :addresses, only: %i[new create]

  resources :sessions, only: %i[new create destroy]
  get "logout", to: "sessions#destroy", as: "logout"

  resources :users, only: %i[show new create]

  resources :products, only: %i[index show]
  resources :checkout, only: [:index]

  root to: "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RetroX</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="http://js.stripe.com/v3/"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>

  <body>
    <section class="section">
      <div class="container">

        <nav class="navbar mb-5" role="navigation" aria-label="main navigaion" style="border-bottom: 1px solid grey">
          <div class="navbar-brand">
            <a href="/">
              <h1 class="title is-2">OHG</h1>
            </a>
          </div>

          <div class="navbar-menu">
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link" href="/products">
                Games
              </a>

              <div class="navbar-dropdown">
                <a href="/products"  class="navbar-item">
                  All Games
                </a>
                <%Catagory.all.each do |cat|%>
                  <a class=navbar-item href="/catagories/<%= cat.id %>">
                    <%= cat.name %> Games
                  </a>
                <%end%>
              </div>
            </div>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <% if cart["amount"] > 0%>
                <div class="navbar-item has-dropdown is-hoverable">
                  <a class="navbar-link" href="/checkout">
                    Cart (<%= cart["amount"] %>)
                  </a>

                  <div class="navbar-dropdown">
                    <%cart["items"].each do |item|%>
                      <a class=navbar-item href="<%=product_path(item["id"])%>">
                        <%=item["name"]%> | <%= number_to_currency item["price"]%> x <%= item["amount"]%>
                      </a>

                    <%end%>

                    <a href="/checkout"  class="navbar-item button is-primary">
                      Goto Checkout -->
                    </a>
                  </div>
                </div>
              <%else%>
                <a class="navbar-link">
                  Cart(0)
                </a>
              <%end%>

              <div class="buttons">
                <%if !logged_in?%>
                  <a class="button is-primary" href="<%= new_user_path %>">
                    <strong>Sign up</strong>
                  </a>
                  <a class="button is-light" href="<%= new_session_path %>">
                    Log in
                  </a>
                <%else%>
                  <a class="button is-success/" href="<%=root_url%>users/<%= current_user.id %>">
                    <%= current_user.name %>
                  </a>

                  <a class="button is-danger" href="/logout">
                    Log out
                  </a>
                <%end%>
              </div>
            </div>
          </div>

        </nav>

        <%= yield %>
        <footer class=footer>
        <div class="content has-text-centered border-top pt-5">
          Geoffrey Hodgson -- Dec 2020 | <a href="https://github.com/payne1134">Github</a> | About | Contact
        </div>
      </footer>
      </div>

    </section>

  </body>
</html>